### ISSUE TITLE
[Question, Potential Bug Report]: _render_buffer recursion when trying to modify region files in entities folder

### ISSUE THREAD

**Issue by alexis-evelyn** [twoolie/NBT#155]

**Comment by twoolie** [comment]
I suspect that you've somehow created a loop in the tag graph, and `_render_buffer` is chasing down this loop until it hits the recursion limit. I suspect I should add a loop checker to these recursive functions to try and catch situations like these and give more informative error messages.

Is there a region file that I can run your code against?
