### ISSUE TITLE
'TAG_End' is not defined

### ISSUE THREAD

**Issue by SyndiShanX** [twoolie/NBT#165]
I can't create a list with
`list_ench = TAG_List(name="ench", type=TAG_End)`
as it errors saying with
`NameError: name 'TAG_End' is not defined`

```
from nbt.nbt import *
nbtfile = NBTFile()

list_i = TAG_List(name="i", type=TAG_Compound)
compound_main = TAG_Compound()

compound_tag = TAG_Compound(name="tag")

list_ench = TAG_List(name="ench", type=TAG_End)
compound_tag.tags.append(list_ench)

compound_main.tags.append(compound_tag)
list_i.tags.append(compound_main)
nbtfile.tags.append(list_i)
print(nbtfile.pretty_tree())
```

**Comment by InputBlackBoxOutput** [comment]
I am having a similar issue while defining the following using the package

![image](https://user-images.githubusercontent.com/53337979/204194386-4b914ddc-0b20-47b9-811c-706e379d8267.png)

Did you find a resolution for this?

**Comment by SyndiShanX** [comment]
I don't remember, but I think you just ignore Tag_Ends

**Comment by SyndiShanX** [comment]
If it somehow helps, here's the project I was working on when I ran into this https://github.com/SyndiShanX/Skyblock-Item-NBT-Generator
