### ISSUE TITLE
`Sample_World.tar.gz` missing?

### ISSUE THREAD

**Issue by SupraSummus** [twoolie/NBT#176]
Test scripts depend on a `Sample_World.tar.gz` file, which is fetched from <https://github.com/downloads/twoolie/NBT/Sample_World.tar.gz>.

This is defined in: https://github.com/twoolie/NBT/blob/e6198e8f195276650ddac6d7f7baceb037c817e7/tests/downloadsample.py#L23 This link returns 404 and because of this some tests fail.

I wonder if I am doing something wrong or the url to the file is simply outdated? Where can I find the original file? Or maybe I don't need to have the original file and I can generate one using minecraft?

**Comment by macfreek** [comment]
Thanks for reporting this!
Indeed, the link is outdated. For now, here is a new link, but I do not think this is a stable URL either:
https://github.com/twoolie/NBT/files/13199373/Sample_World.tar.gz
