### ISSUE TITLE
Create method to convert SNBT to json/python dict

### ISSUE THREAD

**Issue by BenjyRead** [twoolie/NBT#188]

**Comment by danielgran** [comment]
do it yourself, thats not an issue

**Comment by BenjyRead** [comment]
> do it yourself, thats not an issue

I honestly forgot about this issue, but this is a silly response. Obviously if I haven't done it myself its because im not familiar enough with the codebase to do it. Like what do you think an issue is? 

Anyways later on I found it is actually in this codebase in the `unpack_nbt` function in [this utilities file](https://github.com/twoolie/NBT/blob/master/examples/utilities.py)

**Comment by danielgran** [comment]
good!
