### ISSUE TITLE
examples/map.py does not support anvil worlds

### ISSUE THREAD

**Issue by iamthad** [twoolie/NBT#65]
As stated on line 178, "map still only supports McRegion maps." Since this is part of the test suite, can this be updated to support Anvil?

**Comment by mfld-fr** [comment]
Example `map` is now supporting Anvil worlds.
Tested after the 'flattening' (with latest MC version 1.13.2).
See MR #103

**Comment by mfld-fr** [comment]
Testing the 'map' example on an pre-"flattened" Anvil world has been added in #106. You could close this issue.
