### ISSUE TITLE
"Read the full spec" link is dead in Readme.md

### ISSUE THREAD

**Issue by Borkason** [twoolie/NBT#99]
> read the full spec at http://www.minecraft.net/docs/NBT.txt

A copy can be found here. Question is, if it's still valid 8 years later:  
https://web.archive.org/web/20100310144708/www.minecraft.net/docs/NBT.txt

**Comment by mfld-fr** [comment]
That link is not only dead, but also points to an old version of the specification. Replaced by a link to the official Minecraft Wiki.

**Comment by mfld-fr** [comment]
Fixed in #102. You can close this one.
